#:schema node_modules/wrangler/config-schema.json
name = "amail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "c4665910b20d4689aade56e1632a8c7d"

[[d1_databases]]
binding = "DB"
database_name = "amail"
database_id = "a1f6997d-f6ed-4b4b-9f02-a5ac0faead97"
preview_database_id = "a1f6997d-f6ed-4b4b-9f02-a5ac0faead97"
migrations_dir = "app/drizzle"

[vars]
COOKIE_SECRET = "HEpjPj6QgtCh"
DOMAIN = "amail.win"
#PASSWORD = "password"
TURNSTILE_SITE_KEY = "0x4AAAAAAA3Z0AIToJScfvph"